spring:
  config:
    import: application-foundation.yml
  application:
    name: authik
  datasource:
    url: jdbc:postgresql://authik-database-primary.dating.se.ifmo.ru:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://authik-database-primary.dating.se.ifmo.ru:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
security:
  auth:
    token:
      sign:
        private: ${TOKEN_SIGN_KEY_PRIVATE}
      duration: PT2H
    telegram:
      token: ${TELEGRAM_BOT_TOKEN}
