extends:
  - spectral:oas
  - https://unpkg.com/@apisyouwonthate/style-guide@1.5.0/dist/ruleset.js
  - https://unpkg.com/@stoplight/spectral-owasp-ruleset/dist/ruleset.mjs
rules:
  # Don't know how to fix this when JWT is used
  oas3-operation-security-defined: off

  # TODO: https://github.com/secs-dev/itmo-dating/issues/41
  operation-operationId: off

  # TODO: https://github.com/secs-dev/itmo-dating/issues/16
  hosts-https-only-oas3: off

  # TODO: https://github.com/secs-dev/itmo-dating/issues/42
  no-numeric-ids: off
  owasp:api1:2023-no-numeric-ids: off

  # TODO: https://github.com/secs-dev/itmo-dating/issues/43
  no-unknown-error-format: off

  # Too hard to follow
  owasp:api4:2023-rate-limit-responses-429: off
  owasp:api4:2023-rate-limit: off

  # Can't suppress it only for healthcheck
  owasp:api2:2023-read-restricted: off
  owasp:api8:2023-define-error-responses-401: off
  owasp:api8:2023-define-error-validation: off

  # Don't want to follow
  api-home: off
  api-health: off
