services:
  matchmaker:
    image: eclipse-temurin:21-jdk-alpine
    volumes:
      - ./backend/matchmaker/app/build/libs/matchmaker-app-1.0.0.jar:/matchmaker.jar
    command: java -jar /matchmaker.jar
    environment:
      POSTGRES_DB: ${ITMO_DATING_MATCHMAKER_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_MATCHMAKER_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_MATCHMAKER_POSTGRES_PASSWORD?:err}
    ports:
      - 8080:8080
    depends_on:
      matchmaker-database:
        condition: service_healthy
  matchmaker-database:
    image: postgres
    environment:
      POSTGRES_DB: ${ITMO_DATING_MATCHMAKER_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_MATCHMAKER_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_MATCHMAKER_POSTGRES_PASSWORD?:err}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 16
  people:
    image: eclipse-temurin:21-jdk-alpine
    volumes:
      - ./backend/people/app/build/libs/people-app-1.0.0.jar:/people.jar
    command: java -jar /people.jar
    environment:
      POSTGRES_DB: ${ITMO_DATING_PEOPLE_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_PEOPLE_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_PEOPLE_POSTGRES_PASSWORD?:err}
    ports:
      - 8081:8080
    depends_on:
      people-database:
        condition: service_healthy
  people-database:
    image: postgres
    environment:
      POSTGRES_DB: ${ITMO_DATING_PEOPLE_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_PEOPLE_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_PEOPLE_POSTGRES_PASSWORD?:err}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 16
  tg-miniapp:
    build:
      context: frontend
    ports:
      - "443:443"
