services:
  authik-0:
    image: ghcr.io/secs-dev/itmo-dating-authik:latest
    build:
      context: ./backend/authik
    environment:
      POSTGRES_DB: ${ITMO_DATING_AUTHIK_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_AUTHIK_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_AUTHIK_POSTGRES_PASSWORD?:err}
      TOKEN_SIGN_KEY_PUBLIC: ${ITMO_DATING_TOKEN_SIGN_KEY_PUBLIC?:err}
      TOKEN_SIGN_KEY_PRIVATE: ${ITMO_DATING_AUTHIK_TOKEN_SIGN_KEY_PRIVATE?:err}
      TELEGRAM_BOT_TOKEN: ${ITMO_DATING_AUTHIK_TELEGRAM_BOT_TOKEN?:err}
      KEY_STORE_PASSWORD: ${ITMO_DATING_KEY_STORE_PASSWORD?:err}
    hostname: authik-0.dating.se.ifmo.ru
    depends_on:
      database:
        condition: service_healthy
      consul:
        condition: service_started
  authik-1:
    extends:
      service: authik-0
    hostname: authik-1.dating.se.ifmo.ru
  matchmaker-0:
    image: ghcr.io/secs-dev/itmo-dating-matchmaker:latest
    build:
      context: ./backend/matchmaker
    environment:
      POSTGRES_DB: ${ITMO_DATING_MATCHMAKER_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_MATCHMAKER_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_MATCHMAKER_POSTGRES_PASSWORD?:err}
      TOKEN_SIGN_KEY_PUBLIC: ${ITMO_DATING_TOKEN_SIGN_KEY_PUBLIC?:err}
      KEY_STORE_PASSWORD: ${ITMO_DATING_KEY_STORE_PASSWORD?:err}
    hostname: matchmaker-0.dating.se.ifmo.ru
    depends_on:
      database:
        condition: service_healthy
      consul:
        condition: service_started
  matchmaker-1:
    extends:
      service: matchmaker-0
    hostname: matchmaker-1.dating.se.ifmo.ru
  people-0:
    image: ghcr.io/secs-dev/itmo-dating-people:latest
    build:
      context: ./backend/people
    environment:
      POSTGRES_DB: ${ITMO_DATING_PEOPLE_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_PEOPLE_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_PEOPLE_POSTGRES_PASSWORD?:err}
      TOKEN_SIGN_KEY_PUBLIC: ${ITMO_DATING_TOKEN_SIGN_KEY_PUBLIC?:err}
      KEY_STORE_PASSWORD: ${ITMO_DATING_KEY_STORE_PASSWORD?:err}
    hostname: people-0.dating.se.ifmo.ru
    depends_on:
      database:
        condition: service_healthy
      consul:
        condition: service_started
  people-1:
    extends:
      service: people-0
    hostname: people-1.dating.se.ifmo.ru
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${ITMO_DATING_POSTGRES_DB?:err}
      POSTGRES_USER: ${ITMO_DATING_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${ITMO_DATING_POSTGRES_PASSWORD?:err}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 16
    hostname: database-primary.dating.se.ifmo.ru
  gateway:
    image: ghcr.io/secs-dev/itmo-dating-gateway:latest
    build:
      context: ./backend/gateway
    environment:
      KEY_STORE_PASSWORD: ${ITMO_DATING_KEY_STORE_PASSWORD?:err}
    ports:
      - "444:8080"
  consul:
    image: ghcr.io/secs-dev/itmo-dating-consul:latest
    build:
      context: ./backend/consul
    hostname: server.dc1.consul
    ports:
      - "127.0.0.1:8500:8500/tcp"
      - "127.0.0.1:8501:8501/tcp"
  tg-miniapp:
    image: ghcr.io/secs-dev/itmo-dating-tg-miniapp:latest
    build:
      context: frontend
    ports:
      - "443:443"
