spring:
  config:
    import: application-service-discovery.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: ${spring.application.name}
    change-log: database/changelog.sql
server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/itmo-dating-backend.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    protocol: TLSv1.3
    enabled-protocols: TLSv1.3
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    url: /openapi/api.yml
    path: /swagger-ui.html
security:
  auth:
    token:
      sign:
        public: ${TOKEN_SIGN_KEY_PUBLIC}
logging:
  level:
    web: INFO
    liquibase: WARN
    r2dbc: DEBUG
  group:
    r2dbc: org.springframework.r2dbc
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr([%level]) %clr(%logger{36}){blue}: %msg%n"
