server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    protocol: TLSv1.3
    enabled-protocols: TLSv1.3
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: database/changelog.sql
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    url: /openapi/api.yml
    path: /swagger-ui.html
security:
  auth:
    token:
      sign:
        public: ${TOKEN_SIGN_KEY_PUBLIC}
