server:
  port: 8080
  ssl:
    certificate: "classpath:cert.pem"
    certificate-private-key: "classpath:privkey.pem"
    trust-certificate: "classpath:chain.pem"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:database/changelog.sql
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    url: /openapi/api.yml
    path: /swagger-ui.html
