spring:
  config:
    import: application-service-discovery.yml,application-tls.yml,configserver:https://config.dating.se.ifmo.ru:8080
  cloud:
    config:
      uri: https://config.dating.se.ifmo.ru:8080
      token: ${ITMO_DATING_VAULT_TOKEN}
      tls:
        enabled: true
        trust-store: classpath:keystore/itmo-dating-backend.p12
        trust-store-password: ${ITMO_DATING_KEY_STORE_PASSWORD}
  datasource:
    url: jdbc:postgresql://${itmo-dating.postgres.host}:5432/${itmo-dating.postgres.db}
    username: ${itmo-dating.postgres.username}
    password: ${itmo-dating.postgres.password}
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://${itmo-dating.postgres.host}:5432/${itmo-dating.postgres.db}
    username: ${itmo-dating.postgres.username}
    password: ${itmo-dating.postgres.password}
  liquibase:
    liquibase-schema: ${spring.application.name}
    change-log: database/changelog.sql
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    url: /openapi/api.yml
    path: /swagger-ui.html
logging:
  level:
    web: INFO
    liquibase: WARN
    r2dbc: DEBUG
  group:
    r2dbc: org.springframework.r2dbc,org.springframework.data.r2dbc,org.jooq.tools.LoggerListener
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr([%level]) %clr(%logger{36}){blue}: %msg%n"
