server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/itmo-dating-backend.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    protocol: TLSv1.3
    enabled-protocols: TLSv1.3
spring:
  cloud:
    gateway:
      routes:

        - id: get-authik-openapi-api-yml
          uri: https://authik:8080
          predicates:
            - Method=GET
            - Path=/openapi/authik/api.yml
          filters:
            - RewritePath=/openapi/authik/api.yml, /openapi/api.yml

        - id: get-matchmaker-openapi-api-yml
          uri: https://matchmaker:8080
          predicates:
            - Method=GET
            - Path=/openapi/matchmaker/api.yml
          filters:
            - RewritePath=/openapi/matchmaker/api.yml, /openapi/api.yml

        - id: get-people-openapi-api-yml
          uri: https://people:8080
          predicates:
            - Method=GET
            - Path=/openapi/people/api.yml
          filters:
            - RewritePath=/openapi/people/api.yml, /openapi/api.yml

        - id: put-authik-auth-telegram-web-app
          uri: https://authik:8080
          predicates:
            - Method=PUT
            - Path=/api/auth/telegram/web-app

        - id: get-matchmaker-suggestions
          uri: https://matchmaker:8080
          predicates:
            - Method=GET
            - Path=/api/suggestions

        - id: post-matchmaker-people-attitudes-incoming
          uri: https://matchmaker:8080
          predicates:
            - Method=POST
            - Path=/api/people/*/attitudes/incoming/*

        - id: delete-matchmaker-attitudes
          uri: https://matchmaker:8080
          predicates:
            - Method=DELETE
            - Path=/api/attitudes

        - id: get-matchmaker-people-matches
          uri: https://matchmaker:8080
          predicates:
            - Method=GET
            - Path=/api/people/{person_id}/matches

        - id: get-people-person-id
          uri: https://people:8080
          predicates:
            - Method=GET
            - Path=/api/people/*

        - id: delete-people-person-id
          uri: https://people:8080
          predicates:
            - Method=DELETE
            - Path=/api/people/*

        - id: patch-people-person-id
          uri: https://people:8080
          predicates:
            - Method=PATCH
            - Path=/api/people/*

        - id: get-people-faculties
          uri: https://people:8080
          predicates:
            - Method=GET
            - Path=/api/faculties

        - id: get-people-locations
          uri: https://people:8080
          predicates:
            - Method=GET
            - Path=/api/locations

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: authik
        url: openapi/authik/api.yml
      - name: matchmaker
        url: openapi/matchmaker/api.yml
      - name: people
        url: openapi/people/api.yml
