spring:
  config:
    import: application-foundation.yml
  application:
    name: people
  datasource:
    url: jdbc:postgresql://people-database-primary.dating.se.ifmo.ru:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://people-database-primary.dating.se.ifmo.ru:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
service:
    matchmaker:
      url: https://matchmaker:8080/api
