server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://matchmaker-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://matchmaker-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:database/changelog.sql
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    url: /openapi/api.yml
    path: /swagger-ui.html
