spring:
  config:
    import: application-foundation.yml
  application:
    name: matchmaker
  datasource:
    url: jdbc:postgresql://matchmaker-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://matchmaker-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
