spring:
  datasource:
    url: jdbc:postgresql://matchmaker-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:database/changelog.sql
