server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/itmo-dating-backend.p12
    key-store-password: ${ITMO_DATING_KEY_STORE_PASSWORD}
    protocol: TLSv1.3
    enabled-protocols: TLSv1.3
client:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/itmo-dating-backend.p12
    key-store-password: ${server.ssl.key-store-password}
    protocol: TLSv1.3
