spring:
  config:
    import: application-tls.yml
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  health:
    diskspace:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
  distribution:
    percentiles-histogram:
      "[http.server.requests]": true
logging:
  level:
    web: INFO
    liquibase: WARN
    r2dbc: DEBUG
    gateway: WARN
  group:
    r2dbc: org.springframework.r2dbc,org.springframework.data.r2dbc,org.jooq.tools.LoggerListener
    gateway: org.springframework.cloud.gateway.route
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr([%level]) %clr(%logger{36}){blue}: %msg%n"
