openapi: 3.0.3
info:
  title: ITMO Dating Matchmaker
  version: 0.0.1
servers:
  - url: /api/v1
paths:
  /monitoring/status:
    get:
      tags: [Monitoring]
      summary: Checks if service is alive
      description: Returns 'ok', if service is alive, else we will cry
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: ok
  /suggestions:
    get:
      tags: [Suggestions]
      summary: Get suggestions
      description: Returns people suggested for a given person
      parameters:
        - name: limit
          in: query
          description: Maximum count of elements to return
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 8
        - name: person_id
          in: query
          description: |
            A person for who suggestions are made.
            If absent, person_id from auth token will be used.
          required: false
          schema:
            $ref: "#/components/schemas/PersonId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PersonId"
                uniqueItems: true
  /people/{target_id}/attitudes:
    post:
      tags: [Suggestions]
      summary: Like or skip a suggestion
      description: Source id is taken from an auth token
      parameters:
        - name: target_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/PersonId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Attitude"
      responses:
        204:
          description: Attitude is taken into account
        400:
          description: Source already posted an attitude to target
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
  /people/{person_id}/matches:
    get:
      tags: [Suggestions]
      summary: Get person matches
      description: Returns people who mutually liked given person
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PersonId"
                uniqueItems: true
components:
  schemas:
    PersonId:
      type: integer
      description: A unique key of a person, autogenerated
      format: int64
      minimum: 1
      example: 12345678
    Attitude:
      type: object
      properties:
        verdict:
          type: string
          enum:
            - like
            - skip
      required:
        - verdict
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: HTTP Status Code
          example: 400
        status:
          type: string
          description: HTTP Status Description
          example: Bad Request
        message:
          type: string
          description: Detailed Message
          example: Username must contain only latin letter
      required:
        - code
        - status
        - message
