spring:
  config:
    import: application-tls.yml,application-monitoring.yml
  cloud:
    consul:
      scheme: https
      host: server.dc1.consul
      port: 8501
      tls:
        key-store-instance-type: JKS
        certificate-path: keystore/itmo-dating-backend.jks
        certificate-password: ${server.ssl.key-store-password}
        key-store-path: keystore/itmo-dating-backend.jks
        key-store-password: ${server.ssl.key-store-password}
      discovery:
        enabled: true
        scheme: https
        instance-id: instance-${HOSTNAME}
        heartbeat:
          enabled: true
          ttl: 30
        catalog-services-watch-delay: 5000
management:
  health:
    consul:
      enabled: true
