spring:
  cloud:
    consul:
      scheme: https
      host: server.dc1.consul
      port: 8501
      tls:
        key-store-instance-type: JKS
        certificate-path: keystore/itmo-dating-backend.jks
        certificate-password: ${server.ssl.key-store-password}
        key-store-path: keystore/itmo-dating-backend.jks
        key-store-password: ${server.ssl.key-store-password}
      discovery:
        enabled: true
        scheme: https
        instance-id: ${HOSTNAME}
        heartbeat:
          enabled: true
management:
  health:
    consul:
      enabled: true
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
