spring:
  config:
    import: application-service-discovery.yml,application-tls.yml
  application:
    name: config
  profiles:
    active: vault
  cloud:
    config:
      server:
        vault:
          scheme: https
          host: vault.dating.se.ifmo.ru
          port: 8200
          kv-version: 1
          backend: itmo-dating
          skip-ssl-validation: true
          ssl:
            key-store: ${server.ssl.key-store}
            key-store-password: ${server.ssl.key-store-password}
            trust-store: ${client.ssl.key-store}
            trust-store-password: ${client.ssl.key-store-password}
