apiVersion: 1
datasources:

  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    url: http://${ITMO_DATING_PROMETHEUS_HOST}:9090
    isDefault: true

  - name: Loki
    label: Loki
    type: loki
    access: proxy
    url: http://${ITMO_DATING_LOKI_HOST}:3100
