name: Gradle

on:
  push:
    branches: 
      - main
      - lab-[1234]
  pull_request:
    branches:
      - main
      - lab-[1234]

jobs:
  build:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint OpenAPI Specifications
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'backend/*/src/main/resources/static/openapi/api.yml'
          spectral_ruleset: backend/config/.spectral.yaml

      - name: Setup up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Key Pair
        run: bash config/crypto/keys.bash generate test

      - name: Build
        run: gradle build
