name: Maven

on:
  push:
    branches: 
      - main
      - lab-[1234]
  pull_request:
    branches:
      - main
      - lab-[1234]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compile
        run: mvn compile

      - name: Unit Test
        run: mvn test

      - name: Package
        run: mvn package
